### PR TITLE
adding basic info to readme

### PR DESCRIPTION
**Pull request by choldgraf**
This adds the beginning structures for governance, scope, roadmaps, and meetings.

### CODE REVIEW

**Comment by choldgraf** [comment]
arg I just saw that #2 was opened. I opted here to just link to hackmd files, since it's one less step to remember to do. However, I'd also be +1 on copy/pasting it into markdown files as @jlpalomino suggests to do if everybody else is cool with that. What do folks think?

**Comment by choldgraf** [comment]
cc @lwasser in case you missed this :-)

**Comment by lwasser** [comment]
watching this repo now. i did miss this! i think links are ok to start but if we are using git we probably should use git and github ya know?  ie copy things over but at a min add links to start.

**Comment by lwasser** [comment]
This is a great start @choldgraf  thank you. i'll merge this for now and we can continue to build it out. 
cc'ing  @cboettig & @karthik just in case they want to keep tabs on us! :)

**Pull request merged**
